/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'demian' at '12/13/13 2:02 PM' with Gradle 1.9
 *
 * @author demian, @date 12/13/13 2:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
